// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsyxlkpudwjqzzxgrxsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzeXhsa3B1ZHdqcXp6eGdyeHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTA3NzMsImV4cCI6MjA1ODM4Njc3M30.uTGIIrksA6Tmvml9tFfWys5e4ccUAN8YvBNCawF12NA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);